#!/usr/bin/env python3
"""Generate bash patch arrays from vendor/patches.json (SpotX-Windows DB).

Covers others.DisableExp (-> false) and others.EnableExp (-> true) using the
same perl one-liner style as SpotX-Bash:
    <description>",default:\\K!.(?=})  ->  true|false   (s flag, xpuiJs)

Version gates (fr/to) are carried into fields 6/7 so spotx.sh apply_patch
skips non-applicable client versions. Entries without a usable description
are skipped with a warning on stderr.

Usage:
    python3 tools/sync_from_patches.py vendor/patches.json > tools/generated_exp.inc
"""
import json
import re
import sys


def esc_desc(text):
    # Escape regex metachars. Single quotes are bash-escaped as '\'' since
    # output lines are single-quoted.
    return re.escape(text).replace("'", "'\\''")


def entry_to_line(key, e, want):
    ver = e.get("version", {}) or {}
    fr = ver.get("fr", "") or ""
    to = ver.get("to", "") or ""
    desc = e.get("native_description") or e.get("description") or ""
    desc = desc.strip()
    if not desc:
        print(f"WARN: {key}: no description, skipped", file=sys.stderr)
        return None
    pat = esc_desc(desc)
    match = f'{pat}",default:\\K!.(?=}})'
    repl = "true" if want else "false"
    # name|match|replace|flags|file|fr|to
    return f"'gen_{key}&{match}&{repl}&s&xpuiJs&{fr}&{to}'"


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "vendor/patches.json"
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    others = data.get("others", {})
    dis = others.get("DisableExp", {})
    ena = others.get("EnableExp", {})

    dis_lines, ena_lines = [], []
    for k in sorted(dis):
        line = entry_to_line(k, dis[k], False)
        if line:
            dis_lines.append(line)
    for k in sorted(ena):
        line = entry_to_line(k, ena[k], True)
        if line:
            ena_lines.append(line)

    print("# AUTO-GENERATED by tools/sync_from_patches.py — do not hand-edit.")
    print(f"# Source: vendor/patches.json ({len(dis_lines)} disable, {len(ena_lines)} enable)")
    print("genDisableEx=(")
    for line in dis_lines:
        print(line)
    print(")")
    print("genEnableEx=(")
    for line in ena_lines:
        print(line)
    print(")")

    print(f"Generated {len(dis_lines)} disable + {len(ena_lines)} enable entries",
          file=sys.stderr)


if __name__ == "__main__":
    main()
