#!/usr/bin/env python3
"""Generate bash patch arrays from vendor/patches.json (SpotX-Windows DB).

Covers others.DisableExp (-> false) and others.EnableExp (-> true) using the
same perl one-liner style as SpotX-Bash:
    <description>",default:\\K!.(?=})  ->  true|false   (s flag, xpuiJs)

Version gates (fr/to) are carried into fields 6/7 so spotx.sh apply_patch
skips non-applicable client versions. Entries without a usable description
are skipped with a warning on stderr.

Usage:
    python3 tools/sync_from_patches.py vendor/patches.json > tools/generated_exp.inc
"""
import json
import re
import sys


def esc_desc(text):
    # Escape regex metachars. Single quotes are bash-escaped as '\'' since
    # output lines are single-quoted.
    return re.escape(text).replace("'", "'\\''")


def entry_to_line(key, e, want):
    ver = e.get("version", {}) or {}
    fr = ver.get("fr", "") or ""
    to = ver.get("to", "") or ""
    desc = e.get("native_description") or e.get("description") or ""
    desc = desc.strip()
    if not desc:
        print(f"WARN: {key}: no description, skipped", file=sys.stderr)
        return None
    pat = esc_desc(desc)
    match = f'{pat}",default:\\K!.(?=}})'
    repl = "true" if want else "false"
    # name|match|replace|flags|file|fr|to
    return f"'gen_{key}&{match}&{repl}&s&xpuiJs&{fr}&{to}'"


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "vendor/patches.json"
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    others = data.get("others", {})
    dis = others.get("DisableExp", {})
    ena = others.get("EnableExp", {})
    cus = others.get("CustomExp", {})

    dis_lines, ena_lines = [], []
    for k in sorted(dis):
        line = entry_to_line(k, dis[k], False)
        if line:
            dis_lines.append(line)
    for k in sorted(ena):
        line = entry_to_line(k, ena[k], True)
        if line:
            ena_lines.append(line)

    # CustomExp: value-flags. Ad-suppressing ones apply always (with the
    # disable set); feature ones apply with the enable set (--noexp skips).
    # Generic shape covers both "...",values:X,default:OLD} and "...",default:OLD}.
    suppress_keys = {
        "AdsDismissTimeInterval", "AdsRefreshTimeInterval",
        "VideosPremiumUpsell", "LyricsUpsell", "OutroPreviewReporting",
    }
    sup_lines, feat_lines = [], []
    for k in sorted(cus):
        e = cus[k]
        ver = e.get("version", {}) or {}
        fr = ver.get("fr", "") or ""
        to = ver.get("to", "") or ""
        desc = (e.get("native_description") or e.get("description") or "").strip()
        value = str(e.get("value", "")).strip()
        if not desc or not value:
            print(f"WARN: custom {k}: missing description/value, skipped",
                  file=sys.stderr)
            continue
        if "&" in value:
            print(f"WARN: custom {k}: value has &, skipped", file=sys.stderr)
            continue
        pat = esc_desc(desc)
        match = f'{pat}"[^}}]{{0,300}}?default:\\K[^,}}]+'
        line = f"'genC_{k}&{match}&{value}&s&xpuiJs&{fr}&{to}'"
        (sup_lines if k in suppress_keys else feat_lines).append(line)

    print("# AUTO-GENERATED by tools/sync_from_patches.py — do not hand-edit.")
    print(f"# Source: vendor/patches.json ({len(dis_lines)} disable, {len(ena_lines)} enable)")
    print("genDisableEx=(")
    for line in dis_lines:
        print(line)
    print(")")
    print("genEnableEx=(")
    for line in ena_lines:
        print(line)
    print(")")
    print("genCustomSuppressEx=(")
    for line in sup_lines:
        print(line)
    print(")")
    print("genCustomEnableEx=(")
    for line in feat_lines:
        print(line)
    print(")")

    print(f"Generated {len(dis_lines)} disable + {len(ena_lines)} enable + "
          f"{len(sup_lines)} custom-suppress + {len(feat_lines)} custom-enable",
          file=sys.stderr)


if __name__ == "__main__":
    main()
